package griffithTest;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

import griffith.Word;

class WordTest {

	// Test case to check if the contains method works correctly
	@Test
    public void testContains() {
		Word word = new Word(new char[]{'h', 'e', 'l', 'l', 'o'});
        assertTrue(word.contains('h'));
        assertFalse(word.contains('z'));
    }

	// Test case to check the length of the word
    @Test
    public void testLength() {
    	Word word = new Word(new char[]{'h', 'e', 'l', 'l', 'o'});
    	assertEquals(5, word.length());
    }

    // Test case to check if getLetters() returns a non-null value
    @Test
    public void testNotNull() {
    	 Word word = new Word(new char[]{'h', 'e', 'l', 'l', 'o'});
         assertNotNull(word.getLetters());
    }

    // Default test method generated by JUnit
	@Test
	void test() {
		fail("Not yet implemented");
	}

}
